#!/usr/bin/env python3
"""Turn media/car-lineart.png into the Braille cars honk draws in the terminal.

Each output character is a 2x4 grid of Braille dots. One car is generated per
requested width, plus `cars.rs`, a Rust table of every size with the row that
holds the bell horn (where the honk bursts out). honk picks the largest car
that fits the terminal. Every row is padded to the same width so the
animation can redraw in place.

Usage (needs Pillow):
    python3 scripts/car_to_braille.py media/car-lineart.png crates/honk/assets/braille 40 48 60 76 96
"""

import sys
from pathlib import Path

from PIL import Image, ImageFilter, ImageOps

# Dot bit for each (x, y) position inside a 2x4 Braille cell (Unicode order).
DOTS = [(0, 0, 0x01), (0, 1, 0x02), (0, 2, 0x04), (1, 0, 0x08),
        (1, 1, 0x10), (1, 2, 0x20), (0, 3, 0x40), (1, 3, 0x80)]
THRESHOLD = 150  # grey level below which a dot is set
HORN_Y = 275     # pixel row of the bell horn's mouth in car-lineart.png


def braille(img: Image.Image, top: int, cols: int) -> tuple[list[str], int]:
    """Render `img` (already cropped; `top` is its offset in the source) at
    `cols` columns. Returns the padded rows and the horn's row index."""
    w, h = img.size
    pw = cols * 2
    # Lines must stay a few dots wide after downscaling: thicken more the
    # more source pixels each dot covers (always an odd filter size, min 3).
    thicken = max(3, round(w / pw * 0.25) | 1)
    ph = round(pw * h / w / 4) * 4
    small = img.filter(ImageFilter.MinFilter(thicken)).resize((pw, ph), Image.LANCZOS)
    rows = []
    for cy in range(ph // 4):
        row = ""
        for cx in range(cols):
            bits = 0
            for dx, dy, bit in DOTS:
                if small.getpixel((cx * 2 + dx, cy * 4 + dy)) < THRESHOLD:
                    bits |= bit
            row += chr(0x2800 + bits) if bits else " "
        rows.append(row)
    horn = int((HORN_Y - top) / h * ph / 4)
    # Drop fully blank rows at the top and bottom, keeping the horn row aligned.
    while rows and not rows[0].strip():
        rows.pop(0)
        horn -= 1
    while rows and not rows[-1].strip():
        rows.pop()
    return rows, horn


def main(src: str, out_dir: str, widths: list[int]) -> None:
    img = Image.open(src).convert("L")
    left, top, right, bottom = ImageOps.invert(img).point(lambda p: 255 if p > 40 else 0).getbbox()
    img = img.crop((left, top, right, bottom))
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    entries = []
    for cols in sorted(widths, reverse=True):
        rows, horn = braille(img, top, cols)
        name = f"car-{cols}.txt"
        (out / name).write_text("\n".join(rows) + "\n", encoding="utf-8")
        entries.append(
            f'    BrailleCar {{ cols: {cols}, rows: {len(rows)}, horn_row: {horn}, '
            f'art: include_str!("{name}") }},'
        )
    (out / "cars.rs").write_text(
        "// Generated by scripts/car_to_braille.py from media/car-lineart.png; do not edit.\n"
        "// Largest first: honk draws the first car that fits the terminal.\n"
        "const BRAILLE_CARS: &[BrailleCar] = &[\n" + "\n".join(entries) + "\n];\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], [int(w) for w in sys.argv[3:]])
