// Generated by scripts/car_to_braille.py from media/car-lineart.png; do not edit.
// Largest first: honk draws the first car that fits the terminal.
const BRAILLE_CARS: &[BrailleCar] = &[
    BrailleCar { cols: 96, rows: 25, horn_row: 4, art: include_str!("car-96.txt") },
    BrailleCar { cols: 76, rows: 20, horn_row: 3, art: include_str!("car-76.txt") },
    BrailleCar { cols: 60, rows: 16, horn_row: 2, art: include_str!("car-60.txt") },
    BrailleCar { cols: 48, rows: 12, horn_row: 2, art: include_str!("car-48.txt") },
    BrailleCar { cols: 40, rows: 10, horn_row: 1, art: include_str!("car-40.txt") },
];
